<?php

declare(strict_types=1);

namespace Galaxon\Quantities\Internal;

use DomainException;
use Galaxon\Core\Exceptions\FormatException;
use Galaxon\Core\Floats;
use Galaxon\Quantities\Currencies\CurrencyService;
use Galaxon\Quantities\Services\ConversionService;
use Galaxon\Quantities\Services\DimensionService;
use Galaxon\Quantities\Services\QuantityTypeService;
use LogicException;

/**
 * Manages unit conversions for a measurement type.
 *
 * This class uses the multiton pattern to maintain a map of dimensions to Converter objects.
 *
 * The class handles:
 * - Validation of units, prefixes, and conversion definitions
 * - Automatic discovery of indirect conversion paths via graph traversal
 * - Prefix algebra for converting between prefixed units
 *
 * The conversion system works by:
 * 1. Storing direct conversions provided in the configuration
 * 2. Automatically inferring additional conversions through:
 *    - Inversion (if a→b exists, compute b→a)
 *    - Composition (if a→c and c→b exist, compute a→b)
 * 3. Applying prefix adjustments when requested units have prefixes
 *
 * All conversions use the linear transformation formula: y = m*x where m is the multiplier.
 *
 * Error tracking: Each conversion has an error score based on numerical precision.
 * The system prefers shorter conversion paths with lower cumulative error.
 */
class Converter
{
    // region Properties

    /**
     * Dimension code for the converter.
     *
     * @var string
     */
    private(set) string $dimension;

    /**
     * Units for this converter.
     *
     * @var array<string, DerivedUnit>
     */
    private(set) array $units = [];

    /**
     * Conversion matrix storing known conversions between units.
     *
     * NB: The source and destination units symbols are the ASCII versions in canonical form.
     *
     * Structure: $conversionMatrix[$srcSymbol][$destSymbol] = Conversion
     *
     * @var array<string, array<string, Conversion>>
     */
    private(set) array $conversionMatrix = [];

    // endregion

    // region Static properties

    /**
     * All the Converters created so far, keyed by dimension.
     *
     * @var array<string, Converter>
     */
    private static array $instances = [];

    // endregion

    // region Constructor

    /**
     * Constructor.
     *
     * Initializes the Converter instance for a given dimension.
     *
     * @param string $dimension Dimension code (e.g. 'L', 'MLT-2').
     * @throws FormatException If the dimension code or any unit codes are invalid.
     * @throws DomainException If units have mismatched dimensions or the factor is non-positive.
     * @throws LogicException If any conversion definition units have the wrong dimension.
     */
    private function __construct(string $dimension)
    {
        // Check the dimension is valid.
        if (!DimensionService::isValid($dimension)) {
            throw new FormatException("Invalid dimension code '$dimension'.");
        }

        // Store the dimension code.
        $this->dimension = $dimension;

        // Load the conversions for known units.
        $this->loadConversionDefinitions();
    }

    // endregion

    // region Methods for managing Converter instances

    /**
     * Get the Converter instance for a given dimension.
     *
     * @param string $dimension Dimension code (e.g. 'L').
     * @return self
     */
    public static function getInstance(string $dimension): self
    {
        // Make sure a Converter for this dimension has been created.
        if (!isset(self::$instances[$dimension])) {
            self::$instances[$dimension] = new self($dimension);
        }

        return self::$instances[$dimension];
    }

    /**
     * Get all the Converter instances created so far.
     *
     * @return array<string, Converter>
     */
    public static function getInstances(): array
    {
        return self::$instances;
    }

    /**
     * Remove the cached Converter instance for a given dimension.
     *
     * @param string $dimension Dimension code to remove.
     */
    public static function removeInstance(string $dimension): void
    {
        unset(self::$instances[$dimension]);
    }

    /**
     * Remove all cached Converter instances.
     *
     * Clears the multiton cache, forcing new instances to be created on next access.
     * Primarily intended for test isolation.
     */
    public static function clearInstances(): void
    {
        self::$instances = [];
    }

    // endregion

    // region Conversion methods

    /**
     * Find the conversion between two units, discovering new paths if necessary.
     *
     * Returns the Conversion object representing the transformation from source to destination unit.
     * The conversion may be:
     * - A unity conversion (factor 1.0) if units are identical
     * - Retrieved from the conversion matrix if previously computed
     * - A prefix-only adjustment if units share the same base
     * - Generated by path-finding through the conversion matrix
     *
     * Discovered conversions are cached in the matrix for future use.
     *
     * @param string|UnitInterface $srcUnit The source unit.
     * @param string|UnitInterface $destUnit The destination unit.
     * @return ?Conversion The conversion, or null if no path exists.
     * @throws DomainException If either unit is invalid.
     * @example
     *   $conversion = $converter->findConversion('m', 'ft');
     */
    public function findConversion(string|UnitInterface $srcUnit, string|UnitInterface $destUnit): ?Conversion
    {
        // Validate the units and convert to DerivedUnit objects.
        $srcUnit = $this->validateUnit($srcUnit);
        $destUnit = $this->validateUnit($destUnit);

        // If the units are identical, return a unity conversion.
        if ($srcUnit->equal($destUnit)) {
            return new Conversion($srcUnit, $destUnit, 1);
        }

        $src = $srcUnit->asciiSymbol;
        $dest = $destUnit->asciiSymbol;

        // If currencies are involved, ensure we have fresh data.
        $dim = $this->dimension;
        if (str_contains($dim, 'C')) {
            CurrencyService::refresh();
        }

        // Make sure both units are in the list.
        $this->addUnit($srcUnit);
        $this->addUnit($destUnit);

        // Ensure merged, unprefixed, and expanded versions of all units ar in the list.
        do {
            $units = $this->units;
            $nAdded = 0;
            foreach ($units as $unit) {
                if ($this->addMerged($unit)) {
                    $nAdded++;
                }
                if ($this->addUnprefixed($unit)) {
                    $nAdded++;
                }
                if ($this->addExpanded($unit)) {
                    $nAdded++;
                }
            }
        } while ($nAdded > 0);

        // Search for the conversion we want until we find it or have run out of options.
        do {
            // Check if we have it.
            if ($this->hasConversion($src, $dest)) {
                return $this->getConversion($src, $dest);
            }

            // Try to find the conversion using a variety of strategies.
            $conversion = $this->findNewConversion($srcUnit, $destUnit);
            if ($conversion !== null) {
                return $conversion;
            }

            // Generate all exact conversions.
            do {
                $nAdded = $this->generateConversions($srcUnit, $destUnit, true);
            } while ($nAdded > 0 && !$this->hasConversion($src, $dest));

            // Check if we have it.
            if ($this->hasConversion($src, $dest)) {
                return $this->getConversion($src, $dest);
            }

            // Generate a batch of new conversions.
            $nAdded = $this->generateConversions($srcUnit, $destUnit);
        } while ($nAdded > 0 && !$this->hasConversion($src, $dest));

        // Return the desired conversion, or null if not found.
        return $this->getConversion($srcUnit, $destUnit);
    }

    /**
     * Get the conversion factor between two unit terms.
     *
     * @param string|UnitInterface $srcUnit The source unit.
     * @param string|UnitInterface $destUnit The destination unit.
     * @return ?float The conversion factor or null if not found.
     * @throws DomainException If either unit term is invalid.
     */
    public function findConversionFactor(string|UnitInterface $srcUnit, string|UnitInterface $destUnit): ?float
    {
        return $this->findConversion($srcUnit, $destUnit)?->factor->value;
    }

    /**
     * Convert a numeric value from one unit to another.
     *
     * Validates both unit symbols, retrieves or computes the conversion, and applies it to the value using the formula
     * y = m*x.
     *
     * @param float $value The value to convert.
     * @param string|UnitInterface $srcUnit The source unit.
     * @param string|UnitInterface $destUnit The destination unit.
     * @return float The converted value.
     * @throws DomainException If either unit symbol is invalid.
     * @throws LogicException If no conversion path exists between the units.
     * @example
     *   $meters = 100;
     *   $feet = $converter->convert($meters, 'm', 'ft');  // 328.084
     */
    public function convert(float $value, string|UnitInterface $srcUnit, string|UnitInterface $destUnit): float
    {
        // Get the conversion factor.
        $factor = $this->findConversionFactor($srcUnit, $destUnit);

        // If no conversion was found, throw an exception.
        if ($factor === null) {
            throw new LogicException(
                "No conversion path found between '$srcUnit' and '$destUnit' (dimension: $this->dimension)."
            );
        }

        // Multiply by the conversion factor.
        return $value * $factor;
    }

    /**
     * Get a conversion from the matrix or null if not found.
     *
     * @param string|DerivedUnit $srcUnit The source unit.
     * @param string|DerivedUnit $destUnit The destination unit.
     * @return ?Conversion The conversion or null if not found.
     */
    public function getConversion(string|DerivedUnit $srcUnit, string|DerivedUnit $destUnit): ?Conversion
    {
        $srcSymbol = is_string($srcUnit) ? $srcUnit : $srcUnit->asciiSymbol;
        $destSymbol = is_string($destUnit) ? $destUnit : $destUnit->asciiSymbol;
        return $this->conversionMatrix[$srcSymbol][$destSymbol] ?? null;
    }

    /**
     * Check if we already have a conversion between two units.
     *
     * @param string|DerivedUnit $srcUnit The source unit.
     * @param string|DerivedUnit $destUnit The destination unit.
     * @return bool True if we have a conversion, false otherwise.
     */
    public function hasConversion(string|DerivedUnit $srcUnit, string|DerivedUnit $destUnit): bool
    {
        return $this->getConversion($srcUnit, $destUnit) !== null;
    }

    // endregion

    // region Methods for modifying unit list

    /**
     * Add the unit to the list.
     *
     * @param DerivedUnit $unit The unit to add.
     */
    public function addUnit(DerivedUnit $unit): void
    {
        $this->units[$unit->asciiSymbol] = $unit;
    }

    /**
     * Remove a unit from the list.
     *
     * @param DerivedUnit $derivedUnit The unit to remove.
     */
    public function removeUnit(DerivedUnit $derivedUnit): void
    {
        unset($this->units[$derivedUnit->asciiSymbol]);
    }

    /**
     * Remove all units from the list.
     */
    public function removeAllUnits(): void
    {
        $this->units = [];
    }

    // endregion

    // region Methods for modifying conversion matrix

    /**
     * Load conversion definitions for this Converter's dimension from the appropriate QuantityType class.
     *
     * @throws FormatException If a unit symbol cannot be parsed.
     * @throws DomainException If the dimensions don't match or the factor is invalid.
     * @throws LogicException If a conversion's dimension doesn't match this Converter.
     */
    public function loadConversionDefinitions(): void
    {
        // Get the quantity type for this dimension.
        $qtyType = QuantityTypeService::getByDimension($this->dimension);
        $conversionDefinitions = $qtyType?->class::getConversionDefinitions() ?? [];

        // Initialize the Converter with all conversion definitions for this dimension.
        foreach (
            $conversionDefinitions as [
                $srcSymbol,
                $destSymbol,
                $factor,
            ]
        ) {
            // Try to get the units as DerivedUnit objects.
            try {
                $srcUnit = DerivedUnit::toDerivedUnit($srcSymbol);
                $destUnit = DerivedUnit::toDerivedUnit($destSymbol);
            } catch (DomainException) {
                // The symbol contains an unknown unit. Skip this conversion definition.
                continue;
            }

            // Construct the Conversion.
            // This will throw if the dimensions don't match or the conversion factor is invalid.
            $conversion = new Conversion($srcUnit, $destUnit, $factor);

            // Add the conversion to the matrix. Don't replace existing.
            // This will throw if the Conversion dimension doesn't match the Converter.
            $this->addConversion($conversion);
        }
    }

    /**
     * Add a conversion to the matrix.
     *
     * @param Conversion $conversion The conversion to add.
     * @param bool $replaceExisting If true, replace any existing conversion between the same units; otherwise, the
     * existing conversion is kept and the method returns false.
     * @return bool True if the conversion was added, false if it already existed and was not replaced.
     * @throws LogicException If the conversion's dimension doesn't match this Converter.
     */
    public function addConversion(Conversion $conversion, bool $replaceExisting = false): bool
    {
        // Verify dimension.
        if ($conversion->dimension !== $this->dimension) {
            throw new LogicException(
                "Cannot add conversion with dimension '$conversion->dimension' to a Converter with dimension " .
                "'{$this->dimension}'."
            );
        }

        // Add the units to the list.
        $this->addUnit($conversion->srcUnit);
        $this->addUnit($conversion->destUnit);

        // Get the array keys.
        $srcSymbol = $conversion->srcUnit->asciiSymbol;
        $destSymbol = $conversion->destUnit->asciiSymbol;

        // Add the conversion if it doesn't exist, or update it if it does, and we want to replace it.
        if (!$this->hasConversion($srcSymbol, $destSymbol) || $replaceExisting) {
            $this->conversionMatrix[$srcSymbol][$destSymbol] = $conversion;
            return true;
        }

        return false;
    }

    /**
     * Remove a specific conversion from the matrix.
     *
     * @param Conversion $conversion The conversion to remove.
     */
    public function removeConversion(Conversion $conversion): void
    {
        unset($this->conversionMatrix[$conversion->srcUnit->asciiSymbol][$conversion->destUnit->asciiSymbol]);
    }

    /**
     * Remove all conversions from the matrix.
     */
    public function removeAllConversions(): void
    {
        $this->conversionMatrix = [];
    }

    /**
     * Remove all conversions involving a given unit.
     *
     * Call this when unloading a Unit from the loaded units.
     *
     * @param Unit $unit The unit whose conversions should be removed.
     */
    public function removeConversionsByUnit(Unit $unit): void
    {
        foreach ($this->conversionMatrix as $srcSymbol => $conversionList) {
            foreach ($conversionList as $destSymbol => $conversion) {
                if ($conversion->involvesUnit($unit)) {
                    unset($this->conversionMatrix[$srcSymbol][$destSymbol]);
                }
            }
        }
    }

    // endregion

    // region Validation methods

    /**
     * Validate a string or object representing a unit.
     *
     * Returns the validated DerivedUnit object if valid and throws an exception if not.
     *
     * @param string|UnitInterface $value The unit value to validate.
     * @return DerivedUnit The validated DerivedUnit object equivalent to the provided parameter.
     * @throws DomainException If the symbol is invalid or the unit has the wrong dimension for this Converter.
     */
    private function validateUnit(string|UnitInterface $value): DerivedUnit
    {
        // Get the unit term as a DerivedUnit object.
        $unit = DerivedUnit::toDerivedUnit($value);

        // Check the unit term has the right dimension.
        if ($unit->dimension !== $this->dimension) {
            $qtyType = QuantityTypeService::getByDimension($this->dimension);
            $error = $qtyType === null
                ? "The unit dimension '$unit->dimension' does not match the converter dimension '$this->dimension'."
                : "The unit '$unit->asciiSymbol' is invalid for $qtyType->name quantities.";
            throw new DomainException($error);
        }

        return $unit;
    }

    // endregion

    // region Conversion helper methods

    /**
     * Look for an inverse conversion between two units.
     *
     * @param DerivedUnit $srcUnit The source unit.
     * @param DerivedUnit $destUnit The destination unit.
     * @return ?Conversion The inverse conversion, or null if not found.
     */
    public function findConversionByInverse(DerivedUnit $srcUnit, DerivedUnit $destUnit): ?Conversion
    {
        return $this->getConversion($destUnit, $srcUnit)?->inv();
    }

    /**
     * Attempt to generate a conversion by multiplying a prefix.
     *
     * @param DerivedUnit $srcUnit The source unit.
     * @param DerivedUnit $destUnit The destination unit.
     * @return ?Conversion The prefixed conversion, or null if not applicable.
     */
    public function findConversionByPrefix(DerivedUnit $srcUnit, DerivedUnit $destUnit): ?Conversion
    {
        // Make sure both derived units have only one unit term.
        if (count($srcUnit->unitTerms) !== 1 || count($destUnit->unitTerms) !== 1) {
            return null;
        }

        // Make sure they both have the same unit.
        $srcUnitTerm = $srcUnit->firstUnitTerm;
        $destUnitTerm = $destUnit->firstUnitTerm;
        if (!$srcUnitTerm->unit->equal($destUnitTerm->unit)) {
            return null;
        }

        // Make sure they have the same exponent.
        if ($srcUnitTerm->exponent !== $destUnitTerm->exponent) {
            return null;
        }

        // Calculate the factor and return the conversion.
        return new Conversion($srcUnit, $destUnit, $srcUnitTerm->multiplier / $destUnitTerm->multiplier);
    }

    /**
     * Attempt to generate a conversion by exponentiating a base conversion.
     *
     * If both units are single-term with the same exponent > 1 (e.g., m² → ft²), finds the conversion between the base
     * units (m → ft) and raises it to the exponent.
     *
     * @param DerivedUnit $srcUnit The source unit.
     * @param DerivedUnit $destUnit The destination unit.
     * @return ?Conversion The exponentiated conversion, or null if not applicable.
     */
    public function findConversionByExponentiation(DerivedUnit $srcUnit, DerivedUnit $destUnit): ?Conversion
    {
        // Make sure both derived units have only one unit term.
        if (count($srcUnit->unitTerms) !== 1 || count($destUnit->unitTerms) !== 1) {
            return null;
        }

        $srcUnitTerm = $srcUnit->firstUnitTerm;
        assert($srcUnitTerm instanceof UnitTerm);

        $destUnitTerm = $destUnit->firstUnitTerm;
        assert($destUnitTerm instanceof UnitTerm);

        // Check they have the same exponent, and it's not equal to 1.
        if (
            $srcUnitTerm->exponent === 1 ||
            $destUnitTerm->exponent === 1 ||
            $srcUnitTerm->exponent !== $destUnitTerm->exponent
        ) {
            return null;
        }

        // Remove the exponents.
        $unexponentiatedSrcUnit = $srcUnitTerm->removeExponent();
        $unexponentiatedDestUnit = $destUnitTerm->removeExponent();

        // Get the converter between unexponentiated units.
        $conversion = ConversionService::find($unexponentiatedSrcUnit, $unexponentiatedDestUnit);

        // Return the conversion raised to the exponent, or null if not found.
        return $conversion?->pow($srcUnitTerm->exponent);
    }

    /**
     * Attempt to generate a conversion by converting each unit term individually.
     *
     * For compound units with multiple terms (e.g., kg·m·s⁻² → lb·ft·s⁻²), finds the conversion for each corresponding
     * pair of unit terms and multiplies the factors together.
     *
     * @param DerivedUnit $srcUnit The source unit.
     * @param DerivedUnit $destUnit The destination unit.
     * @return ?Conversion The combined conversion, or null if not applicable or no path exists.
     */
    public function findConversionByUnitTermPairs(DerivedUnit $srcUnit, DerivedUnit $destUnit): ?Conversion
    {
        // Check the number of unit terms match.
        if (count($srcUnit->unitTerms) !== count($destUnit->unitTerms)) {
            return null;
        }

        // Check we have at least 2 unit terms each.
        if (count($srcUnit->unitTerms) < 2) {
            return null;
        }

        // Generate the conversion factor by multiplying the factors for each term.
        $srcUnitTerms = array_values($srcUnit->unitTerms);
        $destUnitTerms = array_values($destUnit->unitTerms);
        $factor = new FloatWithError(1);
        foreach ($srcUnitTerms as $i => $srcUnitTerm) {
            $destUnitTerm = $destUnitTerms[$i];

            // Check the dimensions match.
            if ($srcUnitTerm->dimension !== $destUnitTerm->dimension) {
                return null; // @codeCoverageIgnore
            }

            // Get the conversion.
            $conversion = ConversionService::find($srcUnitTerm, $destUnitTerm);
            if ($conversion === null) {
                return null; // @codeCoverageIgnore
            }

            // Multiply.
            $factor = $factor->mul($conversion->factor);
        }

        return new Conversion($srcUnit, $destUnit, $factor);
    }

    /**
     * Look for a conversion from a source unit to a destination unit via an intermediate unit.
     *
     * Tries four combination strategies and returns the one with the least error:
     * - Sequential:  src→mid + mid→dest  → factor = m1 × m2
     * - Convergent:  src→mid + dest→mid  → factor = m1 / m2
     * - Opposite:    dest→mid + mid→src  → factor = 1 / (m1 × m2)
     * - Divergent:   mid→src + mid→dest  → factor = m2 / m1
     *
     * @param DerivedUnit $srcUnit The source unit.
     * @param DerivedUnit $destUnit The destination unit.
     * @return ?Conversion The conversion, or null if no conversion by this method is found.
     */
    public function findConversionByCombination(DerivedUnit $srcUnit, DerivedUnit $destUnit): ?Conversion
    {
        $src = $srcUnit->asciiSymbol;
        $dest = $destUnit->asciiSymbol;

        $bestConversion = null;
        $minErr = INF;

        // Helper to track the best conversion found.
        $checkCandidate = static function (Conversion $candidate) use (&$bestConversion, &$minErr): bool {
            $err = $candidate->factor->absoluteError;

            // See if it's an improvement.
            if ($err < $minErr) {
                $bestConversion = $candidate;
                $minErr = $err;
            }

            // If the error is 0, we aren't going to do any better, so return.
            return $err === 0.0;
        };

        // Loop 1: Iterate conversions from src (src→mid).
        // This covers sequential (src→mid, mid→dest) and convergent (src→mid, dest→mid) combinations.
        $conversionsFromSrc = $this->conversionMatrix[$src] ?? [];
        foreach ($conversionsFromSrc as $srcToMid) {
            $mid = $srcToMid->destUnit->asciiSymbol;

            // Sequential: src→mid + mid→dest.
            $midToDest = $this->getConversion($mid, $dest);
            if ($midToDest !== null) {
                $newConversion = $srcToMid->combineSequential($midToDest);
                if ($checkCandidate($newConversion)) {
                    return $newConversion;
                }
            }

            // Convergent: src→mid + dest→mid.
            $destToMid = $this->getConversion($dest, $mid);
            if ($destToMid !== null) {
                $newConversion = $srcToMid->combineConvergent($destToMid);
                if ($checkCandidate($newConversion)) {
                    return $newConversion;
                }
            }
        }

        // Loop 2: Iterate conversions from dest (dest→mid).
        // This covers opposite (dest→mid, mid→src) combinations.
        $conversionsFromDest = $this->conversionMatrix[$dest] ?? [];
        foreach ($conversionsFromDest as $destToMid) {
            $mid = $destToMid->destUnit->asciiSymbol;

            // Opposite: dest→mid + mid→src.
            $midToSrc = $this->getConversion($mid, $src);
            if ($midToSrc !== null) {
                $newConversion = $midToSrc->combineOpposite($destToMid);
                if ($checkCandidate($newConversion)) {
                    return $newConversion;
                }
            }
        }

        // Loop 3: Iterate all matrix rows as potential intermediate units.
        // This covers divergent (mid→src, mid→dest) combinations.
        foreach ($this->conversionMatrix as $mid => $conversionsFromMid) {
            if ($mid === $src || $mid === $dest) {
                continue;
            }

            $midToSrc = $conversionsFromMid[$src] ?? null;
            $midToDest = $conversionsFromMid[$dest] ?? null;
            if ($midToSrc !== null && $midToDest !== null) {
                $newConversion = $midToSrc->combineDivergent($midToDest);
                if ($checkCandidate($newConversion)) {
                    return $newConversion;
                }
            }
        }

        return $bestConversion;
    }

    /**
     * Find a conversion between two units.
     *
     * Searches for a conversion path using the following strategies:
     * 1. Inverse of a known conversion
     * 2. Prefix conversion
     * 3. Exponentiation conversion
     * 4. Unit term conversion
     * 5. Combination of 2 conversions via an intermediate unit
     *
     * @param DerivedUnit $srcUnit The source unit.
     * @param DerivedUnit $destUnit The destination unit.
     * @return ?Conversion The conversion, or null if no path exists.
     */
    private function findNewConversion(DerivedUnit $srcUnit, DerivedUnit $destUnit): ?Conversion
    {
        // Defensive programming. These situations would be a misuse of the function.
        // Check that the conversion doesn't already exist.
        if ($this->hasConversion($srcUnit, $destUnit)) {
            throw new LogicException('This conversion is already known.');
        }
        // Check that the units are different.
        if ($srcUnit->equal($destUnit)) {
            throw new LogicException('The units should be different.');
        }

        // Try several strategies to find a conversion and select the best one (i.e. least absolute error).
        $bestConversion = null;
        $minErr = INF;

        // Strategies to try. These are ordered by approximate time cost, so that if an exact conversion is found,
        // we can skip the more expensive strategies.
        $strategies = [
            $this->findConversionByInverse(...),
            $this->findConversionByPrefix(...),
            $this->findConversionByExponentiation(...),
            $this->findConversionByUnitTermPairs(...),
            $this->findConversionByCombination(...),
        ];

        foreach ($strategies as $strategy) {
            /** @var ?Conversion $newConversion */
            $newConversion = $strategy($srcUnit, $destUnit);

            if ($newConversion !== null) {
                $err = $newConversion->factor->absoluteError;

                // If exact, we aren't going to do any better, so return it.
                if ($err === 0.0) {
                    return $newConversion;
                }

                // Check if it's an improvement.
                if ($err < $minErr) {
                    $bestConversion = $newConversion;
                    $minErr = $err;
                }
            }
        }

        // Return the best conversion found, or null if none was found.
        return $bestConversion;
    }

    /**
     * Attempt to generate conversions between all unit pairs using a variety of strategies.
     *
     * Return if and when a conversion for the target pair is found.
     *
     * @param DerivedUnit $srcUnit The source unit of the conversion we're looking for.
     * @param DerivedUnit $destUnit The destination unit of the conversion we're looking for.
     * @param bool $exactOnly Whether to only keep exact conversions.
     * @return int The number of conversions added to the matrix.
     */
    private function generateConversions(DerivedUnit $srcUnit, DerivedUnit $destUnit, bool $exactOnly = false): int
    {
        $nAdded = 0;

        // Check every combination of units. This will add a batch of new conversions to the matrix.
        foreach ($this->units as $curSrcUnit) {
            foreach ($this->units as $curDestUnit) {
                // Skip equal units.
                if ($curSrcUnit->equal($curDestUnit)) {
                    continue;
                }

                // Skip any conversions we already have.
                if ($this->hasConversion($curSrcUnit, $curDestUnit)) {
                    continue;
                }

                // Look for a new conversion.
                $newConversion = $this->findNewConversion($curSrcUnit, $curDestUnit);
                if ($newConversion !== null) {
                    // Add it to the matrix (checking exactness if necessary).
                    if (!$exactOnly || $newConversion->isExact()) {
                        if ($this->addConversion($newConversion)) {
                            $nAdded++;
                        }
                    }

                    // If we've found the one we're looking for, return.
                    if ($this->hasConversion($srcUnit, $destUnit)) {
                        return $nAdded;
                    }
                }
            }
        }

        return $nAdded;
    }

    // endregion

    // region Helper methods for adding unit terms

    /**
     * Attempts to merge compatible unit terms. If successful, adds the new unit and conversion to the Converter.
     *
     * @param DerivedUnit $derivedUnit The unit to check and potentially add a merged variant for.
     * @return bool True if a new conversion was added.
     */
    private function addMerged(DerivedUnit $derivedUnit): bool
    {
        // Check if there's anything to do.
        if (!$derivedUnit->isMergeable()) {
            return false;
        }

        // Get the merged quantity.
        $mergedQty = $derivedUnit->merge();

        // Add the new conversion to the matrix.
        $newConversion = new Conversion($derivedUnit, $mergedQty->derivedUnit, $mergedQty->value);
        return $this->addConversion($newConversion);
    }

    /**
     * Add the unprefixed variant of a unit and an exact conversion between them.
     *
     * Directs the conversion so the conversion factor is an integer, avoiding floating-point error from inexact
     * reciprocals (e.g. 1/1000 for metric prefixes).
     *
     * @param DerivedUnit $derivedUnit The potentially prefixed unit.
     * @return bool True if a new conversion was added.
     */
    private function addUnprefixed(DerivedUnit $derivedUnit): bool
    {
        // Check if there's anything to do.
        if (!$derivedUnit->hasPrefixes()) {
            return false;
        }

        // Get the total prefix multiplier and the unprefixed unit.
        $multiplier = $derivedUnit->multiplier;
        $unprefixedUnit = $derivedUnit->removePrefixes();

        // Work out which is the exact conversion, prefixed => unprefixed or vice versa.
        // This depends on whether the multiplier is less than or greater than 1.
        if ($multiplier >= 1) {
            if (Floats::isApproxInt($multiplier)) {
                $multiplier = round($multiplier);
            }
            $newConversion = new Conversion($derivedUnit, $unprefixedUnit, $multiplier);
        } else {
            $multiplier = 1.0 / $multiplier;
            if (Floats::isApproxInt($multiplier)) {
                $multiplier = round($multiplier);
            }
            $newConversion = new Conversion($unprefixedUnit, $derivedUnit, $multiplier);
        }

        // Add the new conversion to the matrix.
        return $this->addConversion($newConversion);
    }

    /**
     * Attempts to expand the unit. If successful, adds the new unit and conversion to the Converter.
     *
     * @param DerivedUnit $derivedUnit The unit to check and potentially add an expanded variant for.
     * @return bool True if a new conversion was added.
     */
    private function addExpanded(DerivedUnit $derivedUnit): bool
    {
        // Attempt to compute the expanded quantity.
        $expansion = $derivedUnit->tryExpand();

        // If no expansion found, return.
        if ($expansion === null) {
            return false;
        }

        // Add the new conversion to the matrix.
        $newConversion = new Conversion($derivedUnit, $expansion->derivedUnit, $expansion->value);
        return $this->addConversion($newConversion);
    }

    // endregion

    // region Debugging methods

    /**
     * Print the conversion matrix for debugging purposes.
     *
     * @codeCoverageIgnore
     */
    public function printMatrix(): void
    {
        $colWidth = 20;
        $nUnits = count($this->units);
        $line = '+' . str_repeat('-', $colWidth) . '+' .
            str_repeat(str_repeat('-', $colWidth) . '+', $nUnits) . "\n";

        echo $line;
        echo '|' . str_repeat(' ', $colWidth) . '|';
        foreach ($this->units as $unitTerm) {
            echo str_pad($unitTerm->asciiSymbol, $colWidth, ' ', STR_PAD_BOTH) . '|';
        }
        echo "\n";
        echo $line;

        foreach ($this->units as $srcUnit) {
            echo '|' . str_pad($srcUnit->asciiSymbol, $colWidth) . '|';
            foreach ($this->units as $destUnit) {
                $conversion = $this->getConversion($srcUnit, $destUnit);

                if ($conversion !== null) {
                    $mul = $conversion->factor->value;
                    $sMul = sprintf('%.10g', $mul);
                    echo str_pad($sMul, $colWidth);
                } elseif ($srcUnit->asciiSymbol === $destUnit->asciiSymbol) {
                    echo str_pad('1', $colWidth);
                } else {
                    echo str_pad('?', $colWidth);
                }

                echo '|';
            }
            echo "\n";
        }

        echo $line;
    }

    // endregion
}
