<?php

declare(strict_types=1);

namespace Galaxon\Quantities\Internal;

use DomainException;
use Galaxon\Core\Exceptions\FormatException;
use Galaxon\Core\Floats;
use Galaxon\Quantities\Services\CurrencyService;
use Galaxon\Quantities\Services\DimensionService;
use Galaxon\Quantities\Services\QuantityTypeService;
use LogicException;

/**
 * Manages unit conversions for a measurement type.
 *
 * This class uses the multiton pattern to maintain a map of dimensions to Converter objects.
 *
 * The class handles:
 * - Validation of units, prefixes, and conversion definitions
 * - Automatic discovery of indirect conversion paths via graph traversal
 * - Prefix algebra for converting between prefixed units
 *
 * The conversion system works by:
 * 1. Storing direct conversions provided in the configuration
 * 2. Automatically inferring additional conversions through:
 *    - Inversion (if a→b exists, compute b→a)
 *    - Composition (if a→c and c→b exist, compute a→b)
 * 3. Applying prefix adjustments when requested units have prefixes
 *
 * All conversions use the linear transformation formula: y = m*x where m is the multiplier.
 *
 * Error tracking: Each conversion has an error score based on numerical precision.
 * The system prefers shorter conversion paths with lower cumulative error.
 */
class Converter
{
    // region Properties

    /**
     * Dimension code for the converter.
     *
     * @var string
     */
    private(set) string $dimension;

    /**
     * Unprefixed units for this converter.
     *
     * @var array<string, DerivedUnit>
     */
    private(set) array $units = [];

    /**
     * Conversion matrix storing known conversions between units.
     *
     * NB: The source and destination units symbols are the ASCII versions in canonical form.
     *
     * Structure: $conversionMatrix[$srcSymbol][$destSymbol] = Conversion
     *
     * @var ?array<string, array<string, Conversion>>
     */
    private(set) array $conversionMatrix = [];

    // endregion

    // region Static properties

    /**
     * All the Converters created so far, keyed by dimension.
     *
     * @var array<string, Converter>
     */
    private static array $instances = [];

    // endregion

    // region Constructor

    /**
     * Constructor.
     *
     * Initializes the Converter instance for a given dimension.
     *
     * @param string $dimension Dimension code (e.g. 'L', 'MLT-2').
     * @throws FormatException If the dimension code or any unit codes are invalid.
     * @throws DomainException If units have mismatched dimensions or the factor is non-positive.
     * @throws LogicException If any conversion definition units have the wrong dimension.
     */
    private function __construct(string $dimension)
    {
        // Check the dimension is valid.
        if (!DimensionService::isValid($dimension)) {
            throw new FormatException("Invalid dimension code '$dimension'.");
        }

        // Store the dimension code.
        $this->dimension = $dimension;

        // Load the conversions for known units.
        $this->loadConversionsFromDefinitions();
    }

    // endregion

    // region Methods for managing Converter instances

    /**
     * Remove all cached Converter instances.
     *
     * Clears the multiton cache, forcing new instances to be created on next access.
     * Primarily intended for test isolation.
     */
    public static function clearInstances(): void
    {
        self::$instances = [];
    }

    /**
     * Get the Converter instance for a given dimension.
     *
     * @param string $dimension Dimension code (e.g. 'L').
     * @return ?self
     */
    public static function getByDimension(string $dimension): ?self
    {
        // Make sure a Converter for this dimension has been created.
        if (!isset(self::$instances[$dimension])) {
            self::$instances[$dimension] = new self($dimension);
        }

        return self::$instances[$dimension] ?? null;
    }

    /**
     * Get all the Converter instances created so far.
     *
     * @return list<Converter>
     */
    public static function getInstances(): array
    {
        return self::$instances;
    }

    // endregion

    // region Conversion methods

    /**
     * Find the conversion between two unit terms.
     *
     * Returns the Conversion object representing the transformation from source to destination unit term.
     * The conversion may be:
     * - A unity conversion (factor 1.0) if units are identical
     * - Retrieved from the ConversionService if previously computed
     * - A prefix-only adjustment if units share the same base
     * - Generated by pathfinding through the conversion matrix
     *
     * Generated conversions are cached for future use.
     *
     * @param string|UnitInterface $srcUnit The source unit.
     * @param string|UnitInterface $destUnit The destination unit.
     * @return ?Conversion The conversion transformation or null if none found.
     * @throws DomainException If either unit term is invalid.
     * @example
     *   $conversion = $converter->getConversion('m', 'ft');
     */
    public function getConversion(string|UnitInterface $srcUnit, string|UnitInterface $destUnit): ?Conversion
    {
        // Validate the units and convert to DerivedUnit objects.
        $srcUnit = $this->validateUnit($srcUnit);
        $destUnit = $this->validateUnit($destUnit);

        $src = $srcUnit->asciiSymbol;
        $dest = $destUnit->asciiSymbol;

        // If currencies are involved, ensure we have fresh data.
        $dim = $this->dimension;
        if (str_contains($dim, 'C')) {
            CurrencyService::refresh();
        }

        // Make sure both units are in the list.
        $this->addUnit($srcUnit);
        $this->addUnit($destUnit);

        // Make sure all merged and expanded units are in the list, along with their conversions.
        foreach ($this->units as $unit) {
            $this->addMerged($unit);
            $this->addExpanded($unit);
            $this->addUnprefixed($unit);
        }

        // Generate conversions in batches, trying to find the target after each pass.
        do {
            // Check if we have it.
            if (isset($this->conversionMatrix[$src][$dest])) {
                return $this->conversionMatrix[$src][$dest];
            }

            // Try to find the conversion.
            $conversion = $this->findConversion($srcUnit, $destUnit);
            if ($conversion !== null) {
                $this->addConversion($conversion);
                return $conversion;
            }

            // Generate a batch of new conversions.
            $nAdded = $this->generateConversions();
        } while ($nAdded > 0);

        // Return the desired conversion, or null if not found.
        return $this->conversionMatrix[$src][$dest] ?? null;
    }

    /**
     * Get the conversion factor between two unit terms.
     *
     * @param string|UnitInterface $srcUnit The source unit.
     * @param string|UnitInterface $destUnit The destination unit.
     * @return ?float The conversion factor or null if not found.
     * @throws DomainException If either unit term is invalid.
     */
    public function getConversionFactor(string|UnitInterface $srcUnit, string|UnitInterface $destUnit): ?float
    {
        return $this->getConversion($srcUnit, $destUnit)?->factor->value;
    }

    /**
     * Convert a numeric value from one unit to another.
     *
     * Validates both unit symbols, retrieves or computes the conversion, and applies it to the value using the formula
     * y = m*x
     *
     * @param float $value The value to convert.
     * @param string|UnitInterface $srcUnit The source unit.
     * @param string|UnitInterface $destUnit The destination unit.
     * @return float The converted value.
     * @throws DomainException If either unit symbol is invalid.
     * @throws LogicException If no conversion path exists between the units.
     * @example
     *   $meters = 100;
     *   $feet = $converter->convert($meters, 'm', 'ft');  // 328.084
     */
    public function convert(float $value, string|UnitInterface $srcUnit, string|UnitInterface $destUnit): float
    {
        // Get the conversion factor.
        $factor = $this->getConversionFactor($srcUnit, $destUnit);

        // If no conversion was found, throw an exception.
        if ($factor === null) {
            throw new LogicException(
                "No conversion path found between '$srcUnit' and '$destUnit' (dimension: $this->dimension)."
            );
        }

        // Multiply by the conversion factor.
        return $value * $factor;
    }

    // endregion

    // region Methods for modifying unit list

    /**
     * Add the unit to the Converter.
     *
     * @param DerivedUnit $derivedUnit The unit to add.
     */
    public function addUnit(DerivedUnit $derivedUnit): void
    {
        // Add the unit to the list.
        $this->units[$derivedUnit->asciiSymbol] = $derivedUnit;
    }

    /**
     * Remove a unit from the list.
     *
     * @param DerivedUnit $derivedUnit The unit to remove.
     */
    public function removeUnit(DerivedUnit $derivedUnit): void
    {
        unset($this->units[$derivedUnit->asciiSymbol]);
    }

    /**
     * Remove all units from the list.
     */
    public function removeAllUnits(): void
    {
        $this->units = [];
    }

    // endregion

    // region Methods for modifying conversion matrix

    public function loadConversionsFromDefinitions(): void
    {
        // Get the quantity type for this dimension.
        $qtyType = QuantityTypeService::getByDimension($this->dimension);
        $conversionDefinitions = $qtyType?->class::getConversionDefinitions() ?? [];

        // Initialize the Converter with all conversion definitions for this dimension.
        foreach ($conversionDefinitions as [$srcSymbol, $destSymbol, $factor]) {
            // Try to get the units as DerivedUnit objects.
            try {
                $srcUnit = DerivedUnit::toDerivedUnit($srcSymbol);
                $destUnit = DerivedUnit::toDerivedUnit($destSymbol);
            } catch (DomainException) {
                // The symbol contains an unknown unit. Skip this conversion definition.
                continue;
            }

            // Construct the Conversion.
            // This can throw if the dimensions don't match or the conversion factor is invalid.
            $conversion = new Conversion($srcUnit, $destUnit, $factor);

            // Add the conversion to the matrix. Don't replace existing.
            // This can throw if the Conversion dimension doesn't match the Converter.
            $this->addConversion($conversion);
        }
    }

    /**
     * Add a conversion and its inverse to the registry.
     *
     * @param Conversion $conversion The conversion to add.
     * @param bool $replaceExisting Determines action to take if a conversion with the same dimension, source and
     * destination units already exists in the registry. If true, the existing conversion will be replaced; otherwise,
     * the operation will be terminated.
     * @throws LogicException If the given Conversion has a different dimension than the Converter.
     */
    public function addConversion(Conversion $conversion, bool $replaceExisting = false): bool
    {
        // Verify dimension.
        if ($conversion->dimension !== $this->dimension) {
            throw new LogicException(
                "Cannot add conversion with dimension '$conversion->dimension' to a Converter with dimension " .
                "'{$this->dimension}'."
            );
        }

        // Add the units to the list.
        $this->addUnit($conversion->srcUnit);
        $this->addUnit($conversion->destUnit);

        // Get the array keys.
        $srcSymbol = $conversion->srcUnit->asciiSymbol;
        $destSymbol = $conversion->destUnit->asciiSymbol;

        // Add the conversion if it doesn't exist, or update it if it does, and we want to replace it.
        if (!isset($this->conversionMatrix[$srcSymbol][$destSymbol]) || $replaceExisting) {
            $this->conversionMatrix[$srcSymbol][$destSymbol] = $conversion;
            return true;
        }

        //        echo "Added conversion $conversion to Converter('{$this->dimension}')\n";

        return false;
    }

    public function removeConversion(Conversion $conversion): void
    {
        unset($this->conversionMatrix[$conversion->srcUnit->asciiSymbol][$conversion->destUnit->asciiSymbol]);
    }

    public function removeAllConversions(): void
    {
        $this->conversionMatrix = [];
    }

    /**
     * Remove all conversions involving a given unit.
     *
     * Call this when unloading a Unit from the loaded units.
     *
     * @param Unit $unit
     */
    public function removeConversionsByUnit(Unit $unit): void
    {
        foreach ($this->conversionMatrix as $srcSymbol => $conversionList) {
            foreach ($conversionList as $destSymbol => $conversion) {
                if ($conversion->involvesUnit($unit)) {
                    unset($this->conversionMatrix[$srcSymbol][$destSymbol]);
                }
            }
        }
    }

    // endregion

    // region Additional modification methods

    public function clear(): void
    {
        $this->removeAllUnits();
        $this->removeAllConversions();
    }

    // endregion

    // region Validation methods

    /**
     * Validate a string or object representing a unit.
     *
     * Returns the validated DerivedUnit object if valid and throws an exception if not.
     *
     * @param string|UnitInterface $value The unit value to validate.
     * @return DerivedUnit The validated DerivedUnit object equivalent to the provided parameter.
     * @throws DomainException If the symbol is invalid or the unit has the wrong dimension for this Converter.
     */
    public function validateUnit(string|UnitInterface $value): DerivedUnit
    {
        // Get the unit term as a DerivedUnit object.
        $unit = DerivedUnit::toDerivedUnit($value);

        // Check the unit term has the right dimension.
        if ($unit->dimension !== $this->dimension) {
            $qtyType = QuantityTypeService::getByDimension($this->dimension);
            $error = $qtyType === null
                ? "The unit dimension '$unit->dimension' does not match the converter dimension '$this->dimension'."
                : "The unit '$unit->asciiSymbol' is invalid for $qtyType->name quantities.";
            throw new DomainException($error);
        }

        return $unit;
    }

    // endregion

    // region Private conversion helper methods

    /**
     * Attempt to generate a conversion by multiplying a prefix.
     *
     * @param DerivedUnit $srcUnit The source unit.
     * @param DerivedUnit $destUnit The destination unit.
     * @return ?Conversion The prefixed conversion, or null if not applicable.
     */
    private static function findConversionByPrefix(DerivedUnit $srcUnit, DerivedUnit $destUnit): ?Conversion
    {
        // Make sure both derived units have only one unit term.
        if (count($srcUnit->unitTerms) !== 1 || count($destUnit->unitTerms) !== 1) {
            return null;
        }

        // Make sure they both have the same unit.
        $srcUnitTerm = $srcUnit->firstUnitTerm;
        $destUnitTerm = $destUnit->firstUnitTerm;
        if (!$srcUnitTerm->unit->equal($destUnitTerm->unit)) {
            return null;
        }

        // Make sure they both have an exponent of 1.
        if ($srcUnitTerm->exponent !== 1 || $destUnitTerm->exponent !== 1) {
            return null;
        }

        // Calculate the factor and return the conversion.
        return new Conversion($srcUnit, $destUnit, $srcUnitTerm->multiplier / $destUnitTerm->multiplier);
    }

    /**
     * Attempt to generate a conversion by exponentiating a base conversion.
     *
     * If both units are single-term with the same exponent > 1 (e.g., m² → ft²), finds the conversion between the base
     * units (m → ft) and raises it to the exponent.
     *
     * @param DerivedUnit $srcUnit The source unit.
     * @param DerivedUnit $destUnit The destination unit.
     * @return ?Conversion The exponentiated conversion, or null if not applicable.
     */
    private static function findConversionByExponentiation(DerivedUnit $srcUnit, DerivedUnit $destUnit): ?Conversion
    {
        // Make sure both derived units have only one unit term.
        if (count($srcUnit->unitTerms) !== 1 || count($destUnit->unitTerms) !== 1) {
            return null;
        }

        $srcUnitTerm = $srcUnit->firstUnitTerm;
        assert($srcUnitTerm instanceof UnitTerm);

        $destUnitTerm = $destUnit->firstUnitTerm;
        assert($destUnitTerm instanceof UnitTerm);

        // Check they have the same exponent, and it's not equal to 1.
        if (
            $srcUnitTerm->exponent === 1 ||
            $destUnitTerm->exponent === 1 ||
            $srcUnitTerm->exponent !== $destUnitTerm->exponent
        ) {
            return null;
        }

        // Remove the exponents.
        $unexponentiatedSrcUnit = $srcUnitTerm->removeExponent();
        $unexponentiatedDestUnit = $destUnitTerm->removeExponent();

        // Get the converter between unexponentiated units.
        $converter = self::getByDimension($unexponentiatedSrcUnit->dimension);
        $conversion = $converter->getConversion($unexponentiatedSrcUnit, $unexponentiatedDestUnit);

        // Return the conversion raised to the exponent, or null if not found.
        return $conversion?->pow($srcUnitTerm->exponent);
    }

    /**
     * Attempt to generate a conversion by converting each unit term individually.
     *
     * For compound units with multiple terms (e.g., kg·m·s⁻² → lb·ft·s⁻²), finds the conversion for each corresponding
     * pair of unit terms and multiplies the factors together.
     *
     * @param DerivedUnit $srcUnit The source unit.
     * @param DerivedUnit $destUnit The destination unit.
     * @return ?Conversion The combined conversion, or null if not applicable or no path exists.
     */
    private static function findConversionByUnitTermPairs(DerivedUnit $srcUnit, DerivedUnit $destUnit): ?Conversion
    {
        // Check the number of unit terms match.
        if (count($srcUnit->unitTerms) !== count($destUnit->unitTerms)) {
            return null;
        }

        // Check we have at least 2 unit terms each.
        if (count($srcUnit->unitTerms) < 2) {
            return null;
        }

        // Generate the conversion factor by multiplying the factors for each term.
        $srcUnitTerms = array_values($srcUnit->unitTerms);
        $destUnitTerms = array_values($destUnit->unitTerms);
        $factor = new FloatWithError(1);
        foreach ($srcUnitTerms as $i => $srcUnitTerm) {
            $destUnitTerm = $destUnitTerms[$i];

            // Check the dimensions match.
            if ($srcUnitTerm->dimension !== $destUnitTerm->dimension) {
                return null; // @codeCoverageIgnore
            }

            // Get the conversion.
            $converter = self::getByDimension($srcUnitTerm->dimension);
            $conversion = $converter->getConversion($srcUnitTerm, $destUnitTerm);
            if ($conversion === null) {
                return null; // @codeCoverageIgnore
            }

            // Multiply.
            $factor = $factor->mul($conversion->factor);
        }

        return new Conversion($srcUnit, $destUnit, $factor);
    }

    /**
     * Look for a conversion from a source unit to a destination unit via an intermediate unit.
     *
     * Tries three combination strategies and returns the one with the least error:
     * - Sequential:  src→mid + mid→dest  → factor = m1 × m2
     * - Convergent:  src→mid + dest→mid  → factor = m1 / m2
     * - Divergent:   mid→src + mid→dest  → factor = m2 / m1
     *
     * @param UnitInterface $srcUnit The source unit.
     * @param UnitInterface $destUnit The destination unit.
     * @return ?Conversion The conversion, or null if no indirect conversion exists.
     */
    private function findConversionViaIntermediateUnit(UnitInterface $srcUnit, UnitInterface $destUnit): ?Conversion
    {
        $srcUnit = DerivedUnit::toDerivedUnit($srcUnit);
        $destUnit = DerivedUnit::toDerivedUnit($destUnit);

        $src = $srcUnit->asciiSymbol;
        $dest = $destUnit->asciiSymbol;

        $bestConversion = null;
        $minErr = INF;

        // Helper to track the best conversion found.
        $checkCandidate = function (Conversion $candidate) use (&$bestConversion, &$minErr): void {
            if ($candidate->factor->relativeError < $minErr) {
                $bestConversion = $candidate;
                $minErr = $candidate->factor->relativeError;
            }
        };

        // Loop 1: Iterate conversions from src (src→mid).
        // This covers sequential (src→mid, mid→dest) and convergent (src→mid, dest→mid).
        $conversionsFromSrc = $this->conversionMatrix[$src] ?? [];
        foreach ($conversionsFromSrc as $srcToMid) {
            $mid = $srcToMid->destUnit->asciiSymbol;

            // Sequential: src→mid + mid→dest.
            $midToDest = $this->conversionMatrix[$mid][$dest] ?? null;
            if ($midToDest !== null) {
                $checkCandidate($srcToMid->combineSequential($midToDest));
            }

            // Convergent: src→mid + dest→mid.
            $destToMid = $this->conversionMatrix[$dest][$mid] ?? null;
            if ($destToMid !== null) {
                $checkCandidate($srcToMid->combineConvergent($destToMid));
            }
        }

        // Loop 2: Iterate all matrix rows as potential intermediate units.
        // This covers divergent (mid→src, mid→dest).
        foreach ($this->conversionMatrix as $mid => $conversionsFromMid) {
            if ($mid === $src || $mid === $dest) {
                continue;
            }

            $midToSrc = $conversionsFromMid[$src] ?? null;
            $midToDest = $conversionsFromMid[$dest] ?? null;
            if ($midToSrc !== null && $midToDest !== null) {
                $checkCandidate($midToSrc->combineDivergent($midToDest));
            }
        }

        return $bestConversion;
    }

    /**
     * Find a conversion between two units.
     *
     * Searches for a conversion path using the following strategies:
     * 1. Direct matrix lookup
     * 2. Identity (units are equal)
     * 3. Prefix conversion
     * 4. Exponentiation conversion
     * 5. Unit term conversion
     * 6. Inverse of a known conversion
     * 7. Sequential combination through an intermediate unit
     *
     * Found conversions are cached in the ConversionService for future lookups.
     *
     * @param UnitInterface $srcUnit The source unit.
     * @param UnitInterface $destUnit The destination unit.
     * @return ?Conversion The conversion, or null if no path exists.
     */
    private function findConversion(UnitInterface $srcUnit, UnitInterface $destUnit): ?Conversion
    {
        $srcUnit = DerivedUnit::toDerivedUnit($srcUnit);
        $destUnit = DerivedUnit::toDerivedUnit($destUnit);

        // Check for an existing conversion.
        // Ideally, this shouldn't occur - this method is meant for discovering conversions we don't already have.
        $conversion = $this->conversionMatrix[$srcUnit->asciiSymbol][$destUnit->asciiSymbol] ?? null;
        if ($conversion !== null) {
            return $conversion;
        }

        // Check for an identity conversion.
        if ($srcUnit->equal($destUnit)) {
            return new Conversion($srcUnit, $destUnit, 1);
        }

        // Try several strategies to find a conversion and select the best one (least error).
        $bestConversion = null;
        $minErr = INF;

        // Helper function to check for a new best conversion.
        $isExact = function (?Conversion $newConversion) use (&$bestConversion, &$minErr)
        {
            if ($newConversion === null) {
                return false;
            }

            // If the conversion is exact, we're done.
            if ($newConversion->isExact()) {
                return true;
            }

            // Check if this is the new best.
            if ($newConversion->factor->relativeError < $minErr) {
                $bestConversion = $newConversion;
                $minErr = $newConversion->factor->relativeError;
            }
            return false;
        };

        // Check for a conversion via prefix.
        $newConversion = $this->findConversionByPrefix($srcUnit, $destUnit);
        if ($isExact($newConversion)) {
            return $newConversion;
        }

        // Check for a conversion via exponentiation.
        $newConversion = $this->findConversionByExponentiation($srcUnit, $destUnit);
        if ($isExact($newConversion)) {
            return $newConversion;
        }

        // Check for a conversion via unit terms.
        $newConversion = $this->findConversionByUnitTermPairs($srcUnit, $destUnit);
        if ($isExact($newConversion)) {
            return $newConversion;
        }

        // Check for an inverse conversion.
        $conversion = $this->conversionMatrix[$destUnit->asciiSymbol][$srcUnit->asciiSymbol] ?? null;
        if ($conversion !== null) {
            $newConversion = $conversion->inv();
            if ($isExact($newConversion)) {
                return $newConversion;
            }
        }

        // Check for a conversion via an intermediate unit.
        $newConversion = $this->findConversionViaIntermediateUnit($srcUnit, $destUnit);
        if ($isExact($newConversion)) {
            return $newConversion;
        }

        // Return the best conversion found, or null if none could be found.
        return $bestConversion;
    }

    /**
     * Generate a bunch of new conversions between all unit pairs using a variety of strategies.
     *
     * @return int The number of conversions added to the matrix.
     */
    private function generateConversions(): int
    {
        $nAdded = 0;

        // Check every combination of units. This will add a batch of new conversions to the matrix.
        foreach ($this->units as $srcUnit) {
            foreach ($this->units as $destUnit) {
                // Skip any we already have.
                if (isset($this->conversionMatrix[$srcUnit->asciiSymbol][$destUnit->asciiSymbol])) {
                    continue;
                }

                // Look for a new conversion.
                $newConversion = $this->findConversion($srcUnit, $destUnit);
                if ($newConversion !== null) {
                    if ($this->addConversion($newConversion)) {
                        $nAdded++;
                    }
                }
            }
        }

        return $nAdded;
    }

    // endregion

    // region Helper methods for adding unit terms

    /**
     * Attempts to merge compatible unit terms. If successful, adds the new unit and conversion to the Converter.
     *
     * @param DerivedUnit $derivedUnit The unit to check and potentially add a merged variant for.
     * @return void
     */
    private function addMerged(DerivedUnit $derivedUnit): void
    {
        // Check if there's anything to do.
        if (!$derivedUnit->isMergeable()) {
            return;
        }

        // Get the merged quantity.
        $mergedQty = $derivedUnit->merge();

        // Add the new conversion to the matrix.
        $newConversion = new Conversion($derivedUnit, $mergedQty->derivedUnit, $mergedQty->value);
        $this->addConversion($newConversion);
    }

    /**
     * Attempts to expand the unit. If successful, adds the new unit and conversion to the Converter.
     *
     * @param DerivedUnit $derivedUnit The unit to check and potentially add an expanded variant for.
     * @return void
     */
    private function addExpanded(DerivedUnit $derivedUnit): void
    {
        // Attempt to compute the expanded quantity.
        $expansion = $derivedUnit->tryExpand();

        // If no expansion found, return.
        if ($expansion === null) {
            return;
        }

        // Add the new conversion to the matrix.
        $newConversion = new Conversion($derivedUnit, $expansion->derivedUnit, $expansion->value);
        $this->addConversion($newConversion);
    }

    /**
     * Add the unprefixed variant of a unit and an exact conversion between them.
     *
     * Directs the conversion so the conversion factor is an integer, avoiding floating-point error from inexact
     * reciprocals (e.g. 1/1000 for metric prefixes).
     *
     * @param DerivedUnit $derivedUnit The potentially prefixed unit.
     */
    private function addUnprefixed(DerivedUnit $derivedUnit): void
    {
        // Check if there's anything to do.
        if (!$derivedUnit->hasPrefixes()) {
            return;
        }

        // Get the total prefix multiplier and the unprefixed unit.
        $multiplier = $derivedUnit->multiplier;
        $unprefixedUnit = $derivedUnit->removePrefixes();

        // Work out which is the exact conversion, prefixed => unprefixed or vice versa.
        // This depends on whether the multiplier is less than or greater than 1.
        if ($multiplier >= 1) {
            if (Floats::isApproxInt($multiplier)) {
                $multiplier = round($multiplier);
            }
            $newConversion = new Conversion($derivedUnit, $unprefixedUnit, $multiplier);
        } else {
            $multiplier = 1.0 / $multiplier;
            if (Floats::isApproxInt($multiplier)) {
                $multiplier = round($multiplier);
            }
            $newConversion = new Conversion($unprefixedUnit, $derivedUnit, $multiplier);
        }

        // Add the new conversion to the matrix.
        $this->addConversion($newConversion);
    }

    // endregion

    // region Debugging methods

    /**
     * Print the conversion matrix for debugging purposes.
     *
     * @return void
     * @codeCoverageIgnore
     */
    public function printMatrix(): void
    {
        $colWidth = 20;
        $nUnits = count($this->units);
        $line = '+' . str_repeat('-', $colWidth) . '+' .
            str_repeat(str_repeat('-', $colWidth) . '+', $nUnits) . "\n";

        echo $line;
        echo '|' . str_repeat(' ', $colWidth) . '|';
        foreach ($this->units as $unitTerm) {
            echo str_pad($unitTerm->asciiSymbol, $colWidth, ' ', STR_PAD_BOTH) . '|';
        }
        echo "\n";
        echo $line;

        foreach ($this->units as $srcUnit) {
            echo '|' . str_pad($srcUnit->asciiSymbol, $colWidth) . '|';
            foreach ($this->units as $destUnit) {
                $conversion = $this->conversionMatrix[$srcUnit->asciiSymbol][$destUnit->asciiSymbol] ?? null;

                if ($conversion !== null) {
                    $mul = $conversion->factor->value;
                    $sMul = sprintf('%.10g', $mul);
                    echo str_pad($sMul, $colWidth);
                } elseif ($srcUnit->asciiSymbol === $destUnit->asciiSymbol) {
                    echo str_pad('1', $colWidth);
                } else {
                    echo str_pad('?', $colWidth);
                }

                echo '|';
            }
            echo "\n";
        }

        echo $line;
    }

    // endregion
}
